### ISSUE TITLE
include/spdk/util.h: latency_log_ctx 结构体中 io_id 的类型为 uint64_t？

### ISSUE THREAD

**Issue by CS0522** [CS0522/nof-rep#1]
include/spdk/util.h: latency_log_ctx 结构体中 io_id 的类型为 uint64_t，而 ibv_send_wr 的 imm_data 中 imm_data 的类型为 __be32 即大端存储的 unsigned int 为 32 bits 占 4 字节，这里是否需要修改？

**Comment by icecreamai** [comment]
我统一修改成uint32_t吧
